# example_01:

try:
    n1 = float(input('Número 1: '))
    n2 = float(input('Número 2: '))
    result = n1/n2

except Exception as e:
    print(f'Erro - {e}')

else:
    print(f'O resultado é: {result}')

finally:
    print('Fim da Operação!')

# example_02:

try:
    n1 = float(input('Número 1: '))
    n2 = float(input('Número 2: '))
    result = n1/n2

except Exception as e:
    print(f'Erro - {e}')

else:
    print(f'O resultado é: {result}')

finally:
    print('Fim da Operação!')

# example_03:

try:
    n1 = float(input('Número 1: '))
    n2 = float(input('Número 2: '))
    result = n1/n2

except Exception as e:
    print(f'Erro - {e}')

else:
    print(f'O resultado é: {result}')

finally:
    print('Fim da Operação!')

# example_04: Exception

try:
    n1 = float(input('Número 1: '))
    n2 = float(input('Número 2: '))
    result = n1/n2

except Exception as e:
    print(f'Erro - {e}')

else:
    print(f'O resultado é: {result}')

finally:
    print('Fim da Operação!')
